### ISSUE TITLE
GPU CI

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/qulacs2023#24]
GPU Buildもチェックしとかないと後で辛くなる

**Comment by gandalfr-KY** [comment]
現状結構修正点があるのでまとめます
- デバイスのデータをホスト側で読みこむような処理はエラーを起こすのでどうにかする
- constant.hpp の定数がデバイスで使えないので良い設計を検討
- デバイス環境でC++標準ライブラリを使っている部分を修正する
  - Complex を Kokkos::complex に置き換えたので、これにまつわるメソッドも要修正
- 応急処置として CMake ファイルに add_compile_option(-std=c++20) しただけなのでオプションが被っていて汚い。余裕があれば分かる人直す

**Comment by KowerKoint** [comment]
ref: #30
